// ╔═══════════════════════════════════════════════════════════════════════════╗
// ║                        BUILT-IN PRESET DEFINITIONS                        ║
// ║  Configuration data for classic, party, candy, vintage, winter presets    ║
// ╚═══════════════════════════════════════════════════════════════════════════╝

// ═══════════════════════════════════════════════════════════════════════════════
//  PRESETS Object
// ═══════════════════════════════════════════════════════════════════════════════

export const PRESETS = {
    classic: {
        ACTIVE_THEME: 'CHRISTMAS',
        WIRE_THEME: 'CHRISTMAS',
        SOCKET_THEME: 'GOLD',
        ANIMATION_STYLE: 'SOFT_TWINKLE',
        NUM_PINS: 7,
        SAG_AMPLITUDE: 0.5,
        TENSION: 0,
        LIGHTS_PER_SEGMENT: 10,
        BULB_SCALE: 0.08,
        EMISSIVE_INTENSITY: 6,
        POSTFX_ENABLED: true,
        BLOOM_STRENGTH: 0.35,
        BLOOM_RADIUS: 0.2,
        BLOOM_THRESHOLD: 0.2,
        BLOOM_INTENSITY: 0.35,
        GLASS_OPACITY: 1,
        GLASS_ROUGHNESS: 0,
        GLASS_IOR: 2.5,
        WIRE_TWISTS: 120,
        WIRE_THICKNESS: 0.017,
        WIRE_OFFSET: 0.02,
        WIRE_SEPARATION: 0.02,
        ANIMATION_SPEED: 0.6,
        SWAY_X: 0.05,
        SWAY_Z: 0.1,
        TWINKLE_SPEED: 1,
        TWINKLE_MIN_INTENSITY: 0,
        TWINKLE_MAX_INTENSITY: 1,
        TWINKLE_RANDOMNESS: 0,
        SNOW_ENABLED: false,
        SNOW_COUNT: 100,
        SNOW_SPEED: 0.005,
        SNOW_SIZE: 0.01,
        SNOW_DRIFT: 0,
        STARS_ENABLED: false,
        STARS_COUNT: 100,
        STARS_SIZE: 0.1,
        STARS_OPACITY: 0.1,
        STARS_TWINKLE_SPEED: 0,
        BACKGROUND_ENABLED: false,
        AMBIENT_INTENSITY: 1,
        CAMERA_DISTANCE: 22,
        CAMERA_HEIGHT: -3.5,
        CAMERA_X: 0,
        POINT_LIGHTS_ENABLED: false,
        QUALITY: 'medium'
    },
    party: {
        ACTIVE_THEME: 'RAINBOW',
        WIRE_THEME: 'BLACK',
        SOCKET_THEME: 'WIRE_MATCH',
        ANIMATION_STYLE: 'PARTY',
        NUM_PINS: 12,
        SAG_AMPLITUDE: 1,
        TENSION: 0,
        LIGHTS_PER_SEGMENT: 9,
        BULB_SCALE: 0.09,
        EMISSIVE_INTENSITY: 6,
        POSTFX_ENABLED: true,
        BLOOM_STRENGTH: 0.35,
        BLOOM_RADIUS: 0.2,
        BLOOM_THRESHOLD: 0.2,
        BLOOM_INTENSITY: 0.35,
        GLASS_OPACITY: 1,
        GLASS_ROUGHNESS: 0,
        GLASS_IOR: 1.7,
        WIRE_TWISTS: 120,
        WIRE_THICKNESS: 0.02,
        WIRE_OFFSET: 0.02,
        WIRE_SEPARATION: 0.05,
        ANIMATION_SPEED: 1.5,
        SWAY_X: 0.02,
        SWAY_Z: 0.02,
        TWINKLE_SPEED: 1,
        TWINKLE_MIN_INTENSITY: 0,
        TWINKLE_MAX_INTENSITY: 1,
        TWINKLE_RANDOMNESS: 0,
        SNOW_ENABLED: false,
        SNOW_COUNT: 100,
        SNOW_SPEED: 0.005,
        SNOW_SIZE: 0.01,
        SNOW_DRIFT: 0,
        STARS_ENABLED: false,
        STARS_COUNT: 100,
        STARS_SIZE: 0.1,
        STARS_OPACITY: 0.1,
        STARS_TWINKLE_SPEED: 0,
        BACKGROUND_ENABLED: false,
        AMBIENT_INTENSITY: 1,
        CAMERA_DISTANCE: 22,
        CAMERA_HEIGHT: -3.5,
        CAMERA_X: 0,
        POINT_LIGHTS_ENABLED: false,
        QUALITY: 'medium'
    },
    candy: {
        ACTIVE_THEME: 'PASTEL_DREAM',
        WIRE_THEME: 'SILVER',
        SOCKET_THEME: 'SILVER',
        ANIMATION_STYLE: 'RANDOM_SPARKLE',
        NUM_PINS: 9,
        SAG_AMPLITUDE: 0.3,
        TENSION: 0,
        LIGHTS_PER_SEGMENT: 9,
        BULB_SCALE: 0.07,
        EMISSIVE_INTENSITY: 6,
        POSTFX_ENABLED: true,
        BLOOM_STRENGTH: 0.35,
        BLOOM_RADIUS: 0.2,
        BLOOM_THRESHOLD: 0.2,
        BLOOM_INTENSITY: 0.35,
        GLASS_OPACITY: 1,
        GLASS_ROUGHNESS: 0,
        GLASS_IOR: 1.5,
        WIRE_TWISTS: 230,
        WIRE_THICKNESS: 0.009,
        WIRE_OFFSET: 0.015,
        WIRE_SEPARATION: 0.03,
        ANIMATION_SPEED: 2,
        SWAY_X: 0,
        SWAY_Z: 0,
        TWINKLE_SPEED: 1,
        TWINKLE_MIN_INTENSITY: 0,
        TWINKLE_MAX_INTENSITY: 1,
        TWINKLE_RANDOMNESS: 0,
        SNOW_ENABLED: false,
        SNOW_COUNT: 100,
        SNOW_SPEED: 0.005,
        SNOW_SIZE: 0.01,
        SNOW_DRIFT: 0,
        STARS_ENABLED: false,
        STARS_COUNT: 100,
        STARS_SIZE: 0.1,
        STARS_OPACITY: 0.1,
        STARS_TWINKLE_SPEED: 0,
        BACKGROUND_ENABLED: false,
        AMBIENT_INTENSITY: 1,
        CAMERA_DISTANCE: 22,
        CAMERA_HEIGHT: -3.5,
        CAMERA_X: 0,
        POINT_LIGHTS_ENABLED: false,
        QUALITY: 'high'
    },
    vintage: {
        ACTIVE_THEME: 'VINTAGE',
        WIRE_THEME: 'CHRISTMAS',
        SOCKET_THEME: 'COPPER',
        ANIMATION_STYLE: 'ALTERNATING',
        NUM_PINS: 6,
        SAG_AMPLITUDE: 0.8,
        TENSION: 0,
        LIGHTS_PER_SEGMENT: 8,
        BULB_SCALE: 0.1,
        EMISSIVE_INTENSITY: 6,
        POSTFX_ENABLED: true,
        BLOOM_STRENGTH: 0.35,
        BLOOM_RADIUS: 0.2,
        BLOOM_THRESHOLD: 0.2,
        BLOOM_INTENSITY: 0.35,
        GLASS_OPACITY: 1,
        GLASS_ROUGHNESS: 0,
        GLASS_IOR: 2,
        WIRE_TWISTS: 80,
        WIRE_THICKNESS: 0.02,
        WIRE_OFFSET: 0.025,
        WIRE_SEPARATION: 0.025,
        ANIMATION_SPEED: 0.3,
        SWAY_X: 0.08,
        SWAY_Z: 0.05,
        TWINKLE_SPEED: 1,
        TWINKLE_MIN_INTENSITY: 0,
        TWINKLE_MAX_INTENSITY: 1,
        TWINKLE_RANDOMNESS: 0,
        SNOW_ENABLED: false,
        SNOW_COUNT: 100,
        SNOW_SPEED: 0.005,
        SNOW_SIZE: 0.01,
        SNOW_DRIFT: 0,
        STARS_ENABLED: false,
        STARS_COUNT: 100,
        STARS_SIZE: 0.1,
        STARS_OPACITY: 0.1,
        STARS_TWINKLE_SPEED: 0,
        BACKGROUND_ENABLED: true,
        AMBIENT_INTENSITY: 1,
        CAMERA_DISTANCE: 22,
        CAMERA_HEIGHT: -3.5,
        CAMERA_X: 0,
        POINT_LIGHTS_ENABLED: false,
        QUALITY: 'medium'
    },
    winter: {
        ACTIVE_THEME: 'ICY',
        WIRE_THEME: 'SILVER',
        SOCKET_THEME: 'SILVER',
        ANIMATION_STYLE: 'CHASE',
        NUM_PINS: 4,
        SAG_AMPLITUDE: 0.6,
        TENSION: 0,
        LIGHTS_PER_SEGMENT: 33,
        BULB_SCALE: 0.08,
        EMISSIVE_INTENSITY: 6,
        POSTFX_ENABLED: true,
        BLOOM_STRENGTH: 0.35,
        BLOOM_RADIUS: 0.2,
        BLOOM_THRESHOLD: 0.2,
        BLOOM_INTENSITY: 0.35,
        GLASS_OPACITY: 1,
        GLASS_ROUGHNESS: 0,
        GLASS_IOR: 2.2,
        WIRE_TWISTS: 110,
        WIRE_THICKNESS: 0.018,
        WIRE_OFFSET: 0.02,
        WIRE_SEPARATION: 0.022,
        ANIMATION_SPEED: 0.8,
        SWAY_X: 0.03,
        SWAY_Z: 0.12,
        TWINKLE_SPEED: 1,
        TWINKLE_MIN_INTENSITY: 0,
        TWINKLE_MAX_INTENSITY: 1,
        TWINKLE_RANDOMNESS: 0,
        SNOW_ENABLED: false,
        SNOW_COUNT: 100,
        SNOW_SPEED: 0.005,
        SNOW_SIZE: 0.01,
        SNOW_DRIFT: 0,
        STARS_ENABLED: false,
        STARS_COUNT: 100,
        STARS_SIZE: 0.1,
        STARS_OPACITY: 0.1,
        STARS_TWINKLE_SPEED: 0,
        BACKGROUND_ENABLED: false,
        AMBIENT_INTENSITY: 1,
        CAMERA_DISTANCE: 22,
        CAMERA_HEIGHT: -3.5,
        CAMERA_X: 0,
        POINT_LIGHTS_ENABLED: false,
        QUALITY: 'high'
    },
    // ─────────────────────────────────────────────────────────────────────
    //  HERO — used by melty.lol as the iframe embed preset
    //  Loaded via ?embed=1&preset=hero (see js/main.js embed block)
    //  Starting values mirror `classic`; tune freely for hero use.
    // ─────────────────────────────────────────────────────────────────────
    hero: {
        ACTIVE_THEME: 'CHRISTMAS',
        WIRE_THEME: 'CHRISTMAS',
        SOCKET_THEME: 'GOLD',
        ANIMATION_STYLE: 'SOFT_TWINKLE',
        NUM_PINS: 7,
        SAG_AMPLITUDE: 0.5,
        TENSION: 0,
        LIGHTS_PER_SEGMENT: 10,
        BULB_SCALE: 0.08,
        EMISSIVE_INTENSITY: 6,
        POSTFX_ENABLED: true,
        BLOOM_STRENGTH: 0.35,
        BLOOM_RADIUS: 0.2,
        BLOOM_THRESHOLD: 0.2,
        BLOOM_INTENSITY: 0.35,
        GLASS_OPACITY: 1,
        GLASS_ROUGHNESS: 0,
        GLASS_IOR: 2.5,
        WIRE_TWISTS: 120,
        WIRE_THICKNESS: 0.017,
        WIRE_OFFSET: 0.02,
        WIRE_SEPARATION: 0.02,
        ANIMATION_SPEED: 0.6,
        SWAY_X: 0.05,
        SWAY_Z: 0.1,
        TWINKLE_SPEED: 1,
        TWINKLE_MIN_INTENSITY: 0,
        TWINKLE_MAX_INTENSITY: 1,
        TWINKLE_RANDOMNESS: 0,
        SNOW_ENABLED: false,
        SNOW_COUNT: 100,
        SNOW_SPEED: 0.005,
        SNOW_SIZE: 0.01,
        SNOW_DRIFT: 0,
        STARS_ENABLED: false,
        STARS_COUNT: 100,
        STARS_SIZE: 0.1,
        STARS_OPACITY: 0.1,
        STARS_TWINKLE_SPEED: 0,
        BACKGROUND_ENABLED: false,
        AMBIENT_INTENSITY: 1,
        CAMERA_DISTANCE: 22,
        CAMERA_HEIGHT: -3.5,
        CAMERA_X: 0,
        POINT_LIGHTS_ENABLED: false,
        QUALITY: 'medium'
    }
};

// ═══════════════════════════════════════════════════════════════════════════════
//  KEY_MAP for compact export (reduces preset code size by ~70%)
// ═══════════════════════════════════════════════════════════════════════════════

export const KEY_MAP = {
    // Theme & Wire
    ACTIVE_THEME: 'at', WIRE_THEME: 'wt', SOCKET_THEME: 'st',
    // Animation
    ANIMATION_STYLE: 'as', STARS_ENABLED: 'se', SNOW_ENABLED: 'sn',
    BACKGROUND_ENABLED: 'bg',
    // Geometry
    NUM_PINS: 'np', SAG_AMPLITUDE: 'sa', LIGHTS_PER_SEGMENT: 'ls', BULB_SCALE: 'bs',
    WIRE_THICKNESS: 'wk', WIRE_OFFSET: 'wo', WIRE_SEPARATION: 'ws', WIRE_TWISTS: 'ww',
    TENSION: 'tn',
    // Bloom
    POSTFX_ENABLED: 'px', BLOOM_STRENGTH: 'bS', BLOOM_RADIUS: 'bR',
    BLOOM_THRESHOLD: 'bT', BLOOM_INTENSITY: 'bI',
    // Glass
    GLASS_OPACITY: 'go', GLASS_ROUGHNESS: 'gr', EMISSIVE_INTENSITY: 'ei', GLASS_IOR: 'gi',
    // Animation Speed
    ANIMATION_SPEED: 'sp', SWAY_X: 'sx', SWAY_Z: 'sz',
    // Twinkle
    TWINKLE_SPEED: 'ts', TWINKLE_MIN_INTENSITY: 'tm', TWINKLE_MAX_INTENSITY: 'tx',
    // Snow
    SNOW_COUNT: 'sc', SNOW_SPEED: 'ss', SNOW_SIZE: 'si', SNOW_DRIFT: 'sd',
    // Stars
    STARS_COUNT: 'xc', STARS_SIZE: 'xs', STARS_OPACITY: 'xo', STARS_TWINKLE_SPEED: 'xt',
    // Camera
    CAMERA_DISTANCE: 'cd', CAMERA_HEIGHT: 'ch', CAMERA_X: 'cx',
    // Quality
    QUALITY: 'q'
};

// Reverse map for import
export const REVERSE_KEY_MAP = Object.fromEntries(Object.entries(KEY_MAP).map(([k, v]) => [v, k]));
